FROM mysql

MAINTAINER Yuri Barbosa < yuribarbosa123@hotmail.com >

#ENV MYSQL_USER=root \
#    MYSQL_DATABASE=microservice \
#    MYSQL_ROOT_PASSWORD=Qwert78940*

ADD ./usuario.sql /docker-entrypoint-initdb.d